In [44]:
import numpy as np 
import pandas as pd
import sklearn 
from sklearn.model_selection import train_test_split
#import matplotlib.pyplot as plt

In [45]:
df=pd.read_csv("D:/ML Projects/E-Commerce Customer Churn/data/processed/Encoded_customer_data.csv")

In [46]:
df.head()

,Customer_ID,account_age_months,avg_order_value,total_orders,days_since_last_purchase,discount_usage_rate,return_rate,customer_support_tickets,loyalty_member,browsing_frequency_per_week,cart_abandonment_rate,product_review_score_avg,engagement_score,satisfaction_score,price_sensitivity_index,churned
0,0520df14-712d-4c69-a0c5-95a2e7dfc1ff,46,164.96,12,17,0.243,0.1720,0,0,6.1,0.430,5.00,6.58,9.43,3.7,0
1,a4013b3f-0688-4096-a194-6074be8ffec8,3,39.09,4,5,0.591,0.0808,1,0,4.1,0.183,4.44,6.25,8.50,6.9,0
2,eb870f2c-ed3d-4a21-a8ac-273fae69ea4f,29,37.42,8,47,0.212,0.1424,0,0,1.2,0.426,3.87,3.32,8.40,4.3,0
3,a7433451-8ea9-428a-9d80-679c6963b39f,35,62.64,9,3,0.699,0.0128,0,0,3.8,0.730,4.75,6.42,9.71,7.5,0
4,43f81935-49e3-44d3-94d1-5c4715738988,39,113.03,1,7,0.382,0.0232,0,0,5.4,0.613,5.00,6.48,9.92,5.0,0

first i will drop ID column because it identifier and not help me

In [47]:
df=df.drop(columns=['Customer_ID'])

In [48]:
df.head()

,account_age_months,avg_order_value,total_orders,days_since_last_purchase,discount_usage_rate,return_rate,customer_support_tickets,loyalty_member,browsing_frequency_per_week,cart_abandonment_rate,product_review_score_avg,engagement_score,satisfaction_score,price_sensitivity_index,churned
0,46,164.96,12,17,0.243,0.1720,0,0,6.1,0.430,5.00,6.58,9.43,3.7,0
1,3,39.09,4,5,0.591,0.0808,1,0,4.1,0.183,4.44,6.25,8.50,6.9,0
2,29,37.42,8,47,0.212,0.1424,0,0,1.2,0.426,3.87,3.32,8.40,4.3,0
3,35,62.64,9,3,0.699,0.0128,0,0,3.8,0.730,4.75,6.42,9.71,7.5,0
4,39,113.03,1,7,0.382,0.0232,0,0,5.4,0.613,5.00,6.48,9.92,5.0,0

In [49]:
df.columns

Index(['account_age_months', 'avg_order_value', 'total_orders',
       'days_since_last_purchase', 'discount_usage_rate', 'return_rate',
       'customer_support_tickets', 'loyalty_member',
       'browsing_frequency_per_week', 'cart_abandonment_rate',
       'product_review_score_avg', 'engagement_score', 'satisfaction_score',
       'price_sensitivity_index', 'churned'],
      dtype='object')

Feature engineering-->add new features

In [50]:
df['Orders_per_Month']=df['total_orders']/df['account_age_months']+ 1
df['total_customer_spend'] = df['avg_order_value'] * df['total_orders']
df['inactivity_risk_score'] = df['days_since_last_purchase'] / (
    df['browsing_frequency_per_week'] + 1)
df['frustration_index'] = (
    df['customer_support_tickets'] * df['return_rate']
) / (df['satisfaction_score'] + 1)
df['discount_hunter'] = (
    df['discount_usage_rate'] * df['price_sensitivity_index']
)

In [51]:
df.head()

,account_age_months,avg_order_value,total_orders,days_since_last_purchase,discount_usage_rate,return_rate,customer_support_tickets,loyalty_member,browsing_frequency_per_week,cart_abandonment_rate,product_review_score_avg,engagement_score,satisfaction_score,price_sensitivity_index,churned,Orders_per_Month,total_customer_spend,inactivity_risk_score,frustration_index,discount_hunter
0,46,164.96,12,17,0.243,0.1720,0,0,6.1,0.430,5.00,6.58,9.43,3.7,0,1.260870,1979.52,2.394366,0.000000,0.8991
1,3,39.09,4,5,0.591,0.0808,1,0,4.1,0.183,4.44,6.25,8.50,6.9,0,2.333333,156.36,0.980392,0.008505,4.0779
2,29,37.42,8,47,0.212,0.1424,0,0,1.2,0.426,3.87,3.32,8.40,4.3,0,1.275862,299.36,21.363636,0.000000,0.9116
3,35,62.64,9,3,0.699,0.0128,0,0,3.8,0.730,4.75,6.42,9.71,7.5,0,1.257143,563.76,0.625000,0.000000,5.2425
4,39,113.03,1,7,0.382,0.0232,0,0,5.4,0.613,5.00,6.48,9.92,5.0,0,1.025641,113.03,1.093750,0.000000,1.9100

 Train-Test Split

In [52]:
y=df['churned']
x=df.drop(columns=['churned'])

In [53]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20,random_state=42,stratify=y)

In [54]:
print("حجم بيانات التدريب:", xtrain.shape)
print("حجم بيانات الاختبار:", xtest.shape)

حجم بيانات التدريب: (4800, 19)
حجم بيانات الاختبار: (1200, 19)

Encoding & Scaling

In [55]:
from sklearn.preprocessing import StandardScaler

In [56]:
scaler = StandardScaler()
xtrain_scaled=scaler.fit_transform(xtrain)
xtest_scaled=scaler.transform(xtest)

In [57]:
%pip install --force-reinstall --no-deps matplotlib==3.11.1

Collecting matplotlib==3.11.1
  Using cached matplotlib-3.11.1-cp311-cp311-win_amd64.whl.metadata (80 kB)
Using cached matplotlib-3.11.1-cp311-cp311-win_amd64.whl (9.3 MB)
Installing collected packages: matplotlib
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.11.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
error: uninstall-no-record-file

× Cannot uninstall matplotlib 3.11.1
╰─> The package's contents are unknown: no RECORD file was found for matplotlib.

hint: You might be able to recover from this via: pip install --force-reinstall --no-deps matplotlib==3.11.1

In [58]:
#corr_matrix = df.corr(numeric_only=True)
#from matplotlib import pyplot as plt
#import seaborn as sns
# 2. رسم الـ Heatmap
#plt.figure(figsize=(10, 8))
#sns.heatmap(
 #   corr_matrix,
  #  annot=True,  # لكتابة قيم الارتباط جوه المربعات
   # cmap='coolwarm',  # ألوان متدرجة (أزرق للسالب / أحمر للموجب)
    #fmt='.2f',  # تقريب الأرقام لعلامتين عشريتين
    #linewidths=0.5,  # خطوط فاصلة بين المربعات
#)

#plt.title('Correlation Matrix Heatmap', fontsize=14)
#plt.show()

ANOVA F-Test

In [59]:
from sklearn.feature_selection import SelectKBest, f_classif,mutual_info_classif

In [60]:
selector = SelectKBest(score_func=f_classif, k=10)
X_train_selected = selector.fit_transform(xtrain_scaled, ytrain)
X_test_selected = selector.transform(xtrain_scaled)

In [61]:

selected_features = xtrain.columns[selector.get_support()]
print("🎯 الميزات الأقوى اختياراً:/n", list(selected_features))

🎯 الميزات الأقوى اختياراً:/n ['days_since_last_purchase', 'return_rate', 'customer_support_tickets', 'loyalty_member', 'browsing_frequency_per_week', 'product_review_score_avg', 'engagement_score', 'satisfaction_score', 'inactivity_risk_score', 'frustration_index']

In [62]:
df.head()

,account_age_months,avg_order_value,total_orders,days_since_last_purchase,discount_usage_rate,return_rate,customer_support_tickets,loyalty_member,browsing_frequency_per_week,cart_abandonment_rate,product_review_score_avg,engagement_score,satisfaction_score,price_sensitivity_index,churned,Orders_per_Month,total_customer_spend,inactivity_risk_score,frustration_index,discount_hunter
0,46,164.96,12,17,0.243,0.1720,0,0,6.1,0.430,5.00,6.58,9.43,3.7,0,1.260870,1979.52,2.394366,0.000000,0.8991
1,3,39.09,4,5,0.591,0.0808,1,0,4.1,0.183,4.44,6.25,8.50,6.9,0,2.333333,156.36,0.980392,0.008505,4.0779
2,29,37.42,8,47,0.212,0.1424,0,0,1.2,0.426,3.87,3.32,8.40,4.3,0,1.275862,299.36,21.363636,0.000000,0.9116
3,35,62.64,9,3,0.699,0.0128,0,0,3.8,0.730,4.75,6.42,9.71,7.5,0,1.257143,563.76,0.625000,0.000000,5.2425
4,39,113.03,1,7,0.382,0.0232,0,0,5.4,0.613,5.00,6.48,9.92,5.0,0,1.025641,113.03,1.093750,0.000000,1.9100

Mutual Information

In [63]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif
miSelector=SelectKBest(score_func=mutual_info_classif,k=10)
xtrian_mi=miSelector.fit_transform(xtrain_scaled,ytrain)

In [64]:
selected_mi = xtrain.columns[miSelector.get_support()]
print( list(selected_mi))

['avg_order_value', 'days_since_last_purchase', 'discount_usage_rate', 'customer_support_tickets', 'loyalty_member', 'product_review_score_avg', 'engagement_score', 'satisfaction_score', 'price_sensitivity_index', 'inactivity_risk_score']

شرط أساسي وهام جداً في Scikit-Learn!الدالة chi2 في Scikit-Learn لا تقبل إلا القيم الموجبة (Non-negative values).بما إننا عملنا StandardScaler في الخطوات اللي فاتت، فالبيانات بيبقى فيها أرقام سالبة (عشان المتوسط بيبقى $0$). لو جربت تطبق chi2 على xtrain_scaled مباشرة، الـ Python هيديك ValueError: Input X must be non-negative.

In [65]:
from sklearn.feature_selection import SelectKBest, chi2

Wrapper selection ممكن نبدا ب forward selection

In [66]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LogisticRegression

In [67]:
base_model = LogisticRegression(class_weight='balanced', random_state=42)

In [68]:
forward = SequentialFeatureSelector(
    estimator=base_model,
    n_features_to_select=10,
    direction='forward',  # تحديد الإتجاه الأمامي
    scoring='roc_auc',  # معيار التقييم (ممتاز للـ Churn)
    cv=5,  # استخدام 5-Fold Cross Validation لتفادي overfitting
    n_jobs=-1,  # لتسريع العملية باستخدام كل أنوية المعالج
)

In [69]:
forward.fit(xtrain_scaled, ytrain)

SequentialFeatureSelector(estimator=LogisticRegression(class_weight='balanced',
                                                       random_state=42),
                          n_features_to_select=10, n_jobs=-1,
                          scoring='roc_auc')

In [70]:
selected_forward = xtrain.columns[forward.get_support()]
print(list(selected_forward))

['account_age_months', 'avg_order_value', 'days_since_last_purchase', 'discount_usage_rate', 'customer_support_tickets', 'loyalty_member', 'product_review_score_avg', 'engagement_score', 'satisfaction_score', 'inactivity_risk_score']

Exhaustive Feature Selection

In [71]:
%pip install mlxtend

Requirement already satisfied: mlxtend in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (0.25.0)
Requirement already satisfied: scipy>=1.16.3 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: numpy>=2.3.5 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlxtend) (2.4.4)
Requirement already satisfied: pandas>=2.3.3 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlxtend) (3.11.1)
Requirement already satisfied: joblib>=1.5.2 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Requirement already satisfied: pillow>=9 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\O M E N\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [72]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector as EFS
from sklearn.linear_model import LogisticRegression

In [73]:
base_model = LogisticRegression(class_weight='balanced', random_state=42)

In [74]:
efs = EFS(
    estimator=base_model,
    min_features=10,
    max_features=10,
    scoring='roc_auc',
    cv=5,
    n_jobs=-1,
)

In [75]:
#efs.fit(xtrain_scaled, ytrain)

it takes alot of time so i will use REF

In [76]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [77]:
base_model = LogisticRegression(class_weight='balanced', random_state=42)

In [78]:
rfe_selector = RFE(estimator=base_model, n_features_to_select=10, step=1)
rfe_selector.fit(xtrain_scaled, ytrain)

RFE(estimator=LogisticRegression(class_weight='balanced', random_state=42),
    n_features_to_select=10)

In [79]:
selected_rfe = xtrain.columns[rfe_selector.get_support()]
print(list(selected_rfe))

['days_since_last_purchase', 'discount_usage_rate', 'return_rate', 'customer_support_tickets', 'loyalty_member', 'product_review_score_avg', 'engagement_score', 'satisfaction_score', 'total_customer_spend', 'discount_hunter']

In [80]:
df.to_csv("prepared_featureEngineering.csv", index=False)

In [81]:
import joblib

# حفظ البيانات في ملفات مصغرة
joblib.dump(xtrain_scaled, 'X_train_scaled.pkl')
joblib.dump(xtest_scaled, 'X_test_scaled.pkl')
joblib.dump(ytrain, 'y_train.pkl')
joblib.dump(ytest, 'y_test.pkl')

# (اختياري) حفظ الـ Scaler نفسه لاستخدامه مستقبلاً مع أي بيانات جديدة أثناء الـ Deployment
joblib.dump(scaler, 'scaler.pkl')

['scaler.pkl']